import { Albert_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "./components/Static/Navbar";
import Footer from "./components/Static/Footer";
import TopBar from "./components/Static/TopBar";

// Load the Albert Sans font from Google Fonts
const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={albertSans.className}>
      <body className="antialiased overflow-x-hidden">
        <TopBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
